sudo: required
language: generic

services:
  - docker



deploy:
  provider: elasticbeanstalk
  edge: true
  region: "eu-central-1"
  app: "FaradaicSensorDashboard"
  env: "FaradaicSensorDashboard-env"
  bucket_name: "elasticbeanstalk-eu-central-1-505046403352"
  bucket_path: "FaradaICSensorDashBoard"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  
