sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t a6af0n0v/FaradaicSensorsDashboard -f Dockerfile.dev .

script:
  - docker run -e CI=true a6af0n0v/FaradaicSensorsDashboard npm run test